package main

import "fmt"

func main() {

	var p = fmt.Println
	var types string
	types = "bool, string, int32  int64, uint32 uint64, byte // alias for uint8, rune // alias for int32, float32 float64, complex64 complex128."

	fmt.Println("Notes:")
	fmt.Println()
	fmt.Println()
	fmt.Println("Recourses:")
	fmt.Println()
	fmt.Println("If you’re ever stuck on something, check out:")
	fmt.Println()
	fmt.Println("Codecademy's forums")
	fmt.Println("View questions and answers from learners on this site!")
	fmt.Println()
	fmt.Println("Stack Overflow’s Go questions")
	fmt.Println("A forum of programmers answering programming questions.")
	fmt.Println()
	fmt.Println()
	fmt.Println("Go’s official site")
	fmt.Println("Go to the official site for documentation.")
	fmt.Println()
	fmt.Println()
	fmt.Println("Google")
	fmt.Println("Roll up your sleeves and search it up!")
	fmt.Println("It may help to search Golang instead of Go in certain cases.")
	fmt.Println()
	fmt.Println("Using the 'go doc' command is helpful.")
	fmt.Println("You can find out more about a package.")
	fmt.Println("Or about a function inside the package.")
	fmt.Println("EXAMPLE: go doc time.Now")
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println("Comments:")
	fmt.Println()
	fmt.Println("You can create comments with //, or you can make a multi line comment with /* Comment goes here */.")
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println("Variables and Types:")
	fmt.Println()
	fmt.Println("You can create a variable by defining one with var.")
	fmt.Println("You can use that variable in your code as a nickname for your values.")
	fmt.Println("EXAMPLE :")
	fmt.Println("var funFact = \"Hummingbirds' wings can beat up to 200 times a second.\"")
	fmt.Println("fmt.Println(\"Did you know?\")")
	fmt.Println("fmt.Println(funFact)")
	fmt.Println("Output :")
	fmt.Println("Did you know?")
	fmt.Println("Hummingbirds' wings can beat up to 200 times a second.")
	fmt.Println()
	fmt.Println("You can also make a constant. (const)")
	fmt.Println("They Can be used to create a variable that can not be changed later on in the code.")
	fmt.Println()
	fmt.Println("Variables can be assigned different types :", types)
	fmt.Println("The basic types in Go : ints, floats, complexs, and strings.")
	fmt.Println(":= is known as the short declaration operator. It is used to declare and initialize the variables inside and outside the functions.")
	fmt.Println()
	fmt.Println("When defining variables, you can defnie the in single line, for example, ammount, unit := 10, \"dollers\" or you can do it like this:")
	fmt.Println("var ammount, unit int32")
	fmt.Println("ammount = 10")
	fmt.Println("unit = \"dollers\"")
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println("Verbs:")
	fmt.Println()
	fmt.Println("In go there are tags called verbs in the fmt module. Here are some basic verbs used in Go")
	fmt.Println("The %v verb is a is a place holder for variables included within the fmt.Print/ln line.")
	fmt.Println("The %T verb is to title the type of the included variable of the fmt.Print/ln line.")
	fmt.Println("The %% verb is a literal percent sign; consumes no value")
	fmt.Println("the %t is the word true or false")
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println("Operators:")
	fmt.Println()
	fmt.Println("Using an operator can decide how your if/else/else if statement will behave.")
	fmt.Println("Depending on wich operator you use for you block of code, will vary on your outcome of the finnished product.")
	fmt.Println()
	fmt.Println("Here are the basic operators:")
	fmt.Println("==  	 Equal to")
	fmt.Println("!=	 Not equal to")
	fmt.Println(" <	 Less than")
	fmt.Println(" >	 Greater than")
	fmt.Println("<=  	 Less than or equal to")
	fmt.Println(">=	 Greater than or equal to")
	fmt.Println()
	fmt.Println("Logical operators:")
	fmt.Println("&&	And")
	fmt.Println("||	Or")
	fmt.Println(" ! 	Not")
	fmt.Println()
	fmt.Println()
	fmt.Println("Go also has a math/rand library that can be used to create a random number.")
	fmt.Println("This is likely to be used since if you hard caode variables, you know the outcome therefor no need for a if statement.")
	fmt.Println()
	fmt.Println()
	fmt.Println()
	fmt.Println("Functiions:")
	fmt.Println()
	fmt.Println("It’s important to note that the code inside the function body does not run until we call the function.")
	fmt.Println("We can call a function by using it's name followed by a parentheses somewhere outside the definition of the function.")
	fmt.Println("EG: After the function is created, type the functions name with a paren inside of the main function (func main())")
	fmt.Println()
	fmt.Println("Scopes:")
	fmt.Println("A function definition creates something called a scope. We’ve referenced scope before in our conditionals exercise about")
	fmt.Println("scoped short declarations but it’s important to recognize how scope plays a huge role in functions and programming overall!")
	p()
	p("Scope is a concept that refers to where the values and functions are defined and where they can be accessed.")
	p("For instance, when a variable is defined within a function, that variable is only accessible within that function.")
	p("When we try to access that same variable from a different function, we get an error because we can’t do it.")
	p("Each function has its own specific scope.")
	p()
	p("There are three different scopes present in this example:")
	p("The global scope, which contains the function definitions for main() and performAddition().")
	p("performAddition() has a local scope, which defines x and y.")
	p("main() has a local scope also. It can access performAddition() because that’s defined on the same scope level as main() but can’t access the internals of performAddition‘s scope (i.e., x or y).")
	p()
	p("This differentiation of scope keeps the namespace, the available variables and keywords, cleaner as a result. You can only refer to variables or functions defined within a specific namespace.")
	p()
	p("Returning Values from Functions:")
	p()
	p("While variables and their values are scoped to their functions, there are no built-in ways of passing information out of their native functions and into another namespace.")
	p("The way that information can be sent from within a function to the call site, the place where the function is called. ")
	p("This is done by returning a value — when we return a value, we pass the value to another place in our code.")
	p("A function can be given a return type, the type of a value that will be returned by the function.")
	p("We can decide the return type by adding a type after the set of parentheses in the function.")
	p("At the call site, the return value can be stored within a variable of the same type as the function’s return.")
	p("A return statement tells the function to pass back a value (or multiple values) and stops the function from executing any more code, i.e. if we put more code after our return statement, it would not run!")
	p("we can access the variables we need through the return keyword!")
	p("eg.")
	p()
	p("func getLengthOfCentralPark() int32 {")
	p("var lengthInBlocks int32")
	p("lengthInBlocks = 51")
	p("return lengthInBlocks")
	p("}")
	p()
	p("func main() {")
	p("var centralParkLength int32")
	p("centralParkLength = getLengthOfCentralPark()")
	p("fmt.Pln(centralParkLength) // Ps: 51")
	p("}")
	p()
	p("In the example above:")
	p("Inside main() we were able to create a variable centralParkLength with type int32 and store the result (the returned value) from getLengthOfCentralPark() into centralParkLength.")
	p("Then we can check the value of centralParkLength by printing it, which confirms what we said about return by printing the number 51.")
	p("Even though we can’t access lengthInBlocks from getLengthOfCentralPark() directly, we can access the information we need through the return keyword!")
	p()
	p("Using Function Parameters:")
	p()
	p("we can also provide functions with information using parameters.")
	p("Function parameters are variables that are used within the function to use in some sort of computation or calculation.")
	p("When calling a function, we give arguments, which are the values that we want those parameter variables to take.")
	p("We give our function parameters types when defining the function.")
	p()
	p("Reusing Code with Functions:")
	p()
	p("fmt.Println(5 * 5))")
	p("fmt.Println(6 * 6)")
	p("// ...")
	p("fmt.Println(100 * 100)")
	p()
	p("This can quickly get out of hand! Writing all of this down does not align with your programming chops since you can write a function to handle this problem!")
	p()
	p("func squareNum(num int) {")
	p("fmt.Println(num * num)")
	p("}")
	p()
	p("Multiple Return Values:")
	p()
	p("Functions also have to ability to return multiple values.")
	p("after the parentheses which contain our parameters, we need to provide the types of the multiple returns wrapped in their own set of parentheses.")
	p("Also, when we return multiple values, we use a single return keyword followed by the values separated by commas.")
	p()
	p("Deferring Resolution:")
	p()

}
